# NOTEBOOK SETTINGS
[notebook]
dir = "$HOME/Personal/my-notes/"


# NOTE SETTINGS
[note]

language = "en"
default-title = "Untitled"
filename = "{{id}}"
extension = "md"

template = "default.md"

id-charset = "hex"
id-length = 8
id-case = "lower"


# EXTRA VARIABLES
[extra]
author = "Aditya"


# GROUP OVERRIDES
[group.daily]
paths = ["daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"


# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "/bin/zsh"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "cat {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]

# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

# list notes for editing
ls = "zk edit --interactive"

# sear notes by tags
t = "zk edit --interactive --tag $argv"

# new journal entry
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/daily"'

# Open zk config in nvim
config = 'nvim "$HOME/.config/zk/config.toml"'

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
